name: push

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c Release
    - name: Test
      run: dotnet test
    - name: Publish Nuget Panosen.Language
      run: dotnet nuget push Panosen.Language/bin/Release/Panosen.Language.*.nupkg -s https://api.nuget.org/v3/index.json -k ${{secrets.PANOSEN_NUGET_API_KEY}} --skip-duplicate
    - name: Publish Nuget Panosen.Language.CSharp
      run: dotnet nuget push Panosen.Language.CSharp/bin/Release/Panosen.Language.CSharp.*.nupkg -s https://api.nuget.org/v3/index.json -k ${{secrets.PANOSEN_NUGET_API_KEY}} --skip-duplicate
    - name: Publish Nuget Panosen.Language.Java
      run: dotnet nuget push Panosen.Language.Java/bin/Release/Panosen.Language.Java.*.nupkg -s https://api.nuget.org/v3/index.json -k ${{secrets.PANOSEN_NUGET_API_KEY}} --skip-duplicate
    - name: Publish Nuget Panosen.Language.Mysql
      run: dotnet nuget push Panosen.Language.Mysql/bin/Release/Panosen.Language.Mysql.*.nupkg -s https://api.nuget.org/v3/index.json -k ${{secrets.PANOSEN_NUGET_API_KEY}} --skip-duplicate
    - name: Publish Nuget Panosen.Language.Typescript
      run: dotnet nuget push Panosen.Language.Typescript/bin/Release/Panosen.Language.Typescript.*.nupkg -s https://api.nuget.org/v3/index.json -k ${{secrets.PANOSEN_NUGET_API_KEY}} --skip-duplicate
    - name: Publish Nuget Panosen.Language.Vue
      run: dotnet nuget push Panosen.Language.Vue/bin/Release/Panosen.Language.Vue.*.nupkg -s https://api.nuget.org/v3/index.json -k ${{secrets.PANOSEN_NUGET_API_KEY}} --skip-duplicate
